name: "Deploy Action"
description: "CDK Action to Deploy System"

inputs:
  ALLOW_LIST_IPS:
    description: "List of allowed IP addresses separated by commas. No brackets"
    required: true

  DEPLOYMENT_ENVIRONMENT:
    description: "The environment to deploy to (e.g., dev, staging, production)."
    required: true

  LIBRARY_TOKEN_GITHUB:
    description: "Token for accessing the library."
    required: true

  AWS_ACCESS_KEY_ID:
    description: "AWS Access Key ID for deployment."
    required: true

  AWS_SECRET_ACCESS_KEY:
    description: "AWS Secret Access Key for deployment."
    required: true

  AWS_REGION:
    description: "The AWS region to deploy to."
    required: true

  AWS_ACCOUNT:
    description: "The AWS account to deploy to."
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - name: Set Node Version
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install CDK
      shell: bash
      run: npm i -g aws-cdk

    - name: Install Packages
      shell: bash
      run: npm i

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Create Environment File
      shell: bash
      run: |
        touch .env
        echo ALLOW_LIST_IPS=${{ inputs.ALLOW_LIST_IPS }} >> .env
        echo DEPLOYMENT_ENVIRONMENT=${{ inputs.DEPLOYMENT_ENVIRONMENT }} >> .env
        echo AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }} >> .env
        echo LIBRARY_TOKEN_GITHUB=${{ inputs.LIBRARY_TOKEN_GITHUB }} >> .env
        echo AWS_REGION=${{ inputs.AWS_REGION }} >> .env
        echo AWS_ACCOUNT=${{ inputs.AWS_ACCOUNT }} >> .env

    - name: Deploy System
      shell: bash
      run: npm run cdk:deploy:all

    - name: Save Infrastructure Output
      uses: actions/upload-artifact@v3
      with:
        name: infrastructure-output
        path: code/infrastructure/cdk-outputs.json

    - name: Save Cron Job Output
      uses: actions/upload-artifact@v3
      with:
        name: cron-job-output
        path: code/services/cron_jobs/cdk-outputs.json

    - name: Save Live Api Output
      uses: actions/upload-artifact@v3
      with:
        name: live-api-output
        path: code/services/live_api/cdk-outputs.json

    - name: Save Process Tasks Output
      uses: actions/upload-artifact@v3
      with:
        name: process-tasks-output
        path: code/services/process_tasks/cdk-outputs.json

    - name: Save Process Event Output
      uses: actions/upload-artifact@v3
      with:
        name: process-event-output
        path: code/services/process_events/cdk-outputs.json
