name: On Push To Main Branch
on:
  push:
    branches:
      - main

jobs:
  # JOB to deploy stack, run all remote tests, destroy stack
  test_deployment:
    name: Test Deployment
    uses: ./.github/workflows/deploy_test_destroy.yml
    with:
      environment: "develop"
    secrets: inherit

  # JOB to deploy
  deploy:
    name: Deployment
    environment: develop
    needs:
      - test_deployment
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          ALLOW_LIST_IPS: ${{ vars.ALLOW_LIST_IPS }}
          DEPLOYMENT_ENVIRONMENT: ${{ vars.DEPLOYMENT_ENVIRONMENT }}
          LIBRARY_TOKEN_GITHUB: ${{ secrets.LIBRARY_TOKEN_GITHUB }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
